### ISSUE TITLE
[Feature]: Ability to use pre-existing JSONs to scan.

### ISSUE THREAD

**Issue by Surasia** [Cubicpath/HaloInfiniteGetter#71]
### Contact Details

surasiaarchive@gmail.com

### Feature Request

I've been fetching different endpoints from Infinite's API for a few months now, and different items have been removed/changed on those endpoints, yet they still exist on the API. Having the ability to import custom JSONs to scan would help build a broader cache library.

**Comment by Cubicpath** [comment]
Hi there, to clarify you're thinking of a custom list of paths that HaloInfiniteGetter would fetch from halowaypoint and cache, correct? Currently, you can work around by changing the contents of something like `Progression/file/Calendars/Seasons/SeasonCalendar.json` and scanning it. Though it does deserve it's own feature and I'm willing to implement it, perhaps like: 

```json
{
  "recursive": true,
  "paths": [
    "Progression/file/Calendars/Seasons/SeasonCalendar.json",
    "images/file/progression/Switcher/Season_Switcher_S2_LW.png",
    "images/file/progression/ScreenBackgrounds/progression_background.png",
    "progression/file/Seasons/Season7.json"
  ]
}
```

I could also add an option to export all cached requests as path lists too, as opposed to the actual contents. This would avoid the need to share large archives.

**Comment by Surasia** [comment]
I couldn't quite explain it in the initial issue, what I'm trying to do is scan pre-existing JSONs which were cached from Waypoint API, not using InfiniteGetter beforehand. As 343 removes content in endpoints like inventory_guide, it'd help with building a larger repository of GameCMS data/images.

**Comment by Cubicpath** [comment]
Oh alright, so a simple scan selector for local (not in the application cache) json files should be enough. I'll add this in the `Tools` context menu, with the ability to choose multiple files to scan at the same time for convenience.
